@baseUrl = http://localhost:3000/api/auth

### 1. Đăng nhập (Để ghi log lịch sử & lấy Token)
# Username: admin.a
# Password: password123 (Hoặc mật khẩu mới nếu bạn đã đổi)
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "admin.a",
    "password": "password123"
}

### ============================================
### COPY ACCESS TOKEN TỪ BƯỚC 1 DÁN VÀO DƯỚI ĐÂY
### ============================================
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IklEMDAwMSIsInJvbGUiOiJib2QiLCJpYXQiOjE3NjY4NDMyMTcsImV4cCI6MTc2Njg0NjgxN30.pqdOr4GZGtBXjXLxMldrKoRj7TARQtqhg-N_bhIkhkc


### 2. Xem lịch sử đăng nhập
GET {{baseUrl}}/history/resident
Authorization: Bearer {{token}}


### 3. Đổi mật khẩu (Thành công)
POST {{baseUrl}}/change-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "oldPassword": "password123",
    "newPassword": "newpassword456"
}


### 4. Đổi mật khẩu (Thất bại - Sai mật khẩu cũ)
POST {{baseUrl}}/change-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "oldPassword": "sai_mat_khau_cu",
    "newPassword": "newpassword789"
}