@baseUrl = http://localhost:3000/api
@contentType = application/json

# ==================================================================
# 1. SETUP: ĐĂNG NHẬP (LẤY TOKEN)
# ==================================================================

### 1.1. Đăng nhập BAN QUẢN TRỊ (BOD) - Quyền cao nhất
# User: admin.a
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "username": "admin.a",
    "password": "password123"
}

###
# -> Copy Token vào biến @bodToken
@bodToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IklEMDAwMSIsInJvbGUiOiJib2QiLCJpYXQiOjE3NjY4MjE2MjMsImV4cCI6MTc2NjgyNTIyM30.01MkiaeJ4qQuCJu6o6B-zRCqQ21Ih2Yx0ZY21dbbYdc
# ==================================================================

### 1. Tải template (Để xem cấu trúc)
GET {{baseUrl}}/import/export-master-data/?sheet=Admins
Authorization: {{bodToken}}

### 2. Import File (Multipart)
POST {{baseUrl}}/import/master-data
Authorization: {{bodToken}}
Content-Type: multipart/form-data; boundary=boundaryExcel

--boundaryExcel
Content-Disposition: form-data; name="file"; filename="BlueMoon_Full_Data.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< ./BlueMoon_Full_Data.xlsx
--boundaryExcel--