@baseUrl = https://it3180-2025i-se-06.onrender.com/api
@token = DÁN_ACCESS_TOKEN_CUA_ADMIN_VAO_DAY

### 1. Lấy danh sách cư dân
GET {{baseUrl}}/residents
Authorization: Bearer {{token}}

### 2. Thêm cư dân mới
POST {{baseUrl}}/residents
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": "R0099",
    "apartment_id": 1,
    "full_name": "Nguyen Van Test",
    "role": "member",
    "dob": "1995-05-05",
    "gender": "Nam",
    "cccd": "098765432111",
    "phone": "0912345678",
    "email": "test@bluemoon.com"
}